print("Hello! My name is ssBot")
print("I was created in 2021")
name = str(input("Please, remind me ur name"))
print("What a great name u have,", name + '!')
print("Let me guess your age")
print("Enter remainders of divining your age by 3, 5 and 7")
a = int(input())
b = int(input())
c = int(input())
age = (a*70+b*21+c*15)%105
print("Your age is " + str(age) + " that's a good time to start programming!")
